---
# Install and configure GBFS Monitoring Stack
- hosts: gbfs
  gather_facts: true
  become: true
  become_method: sudo

  roles:
    - role: common
      tags: postinstall
    - role: gbfs_stack
      tags: gbfs
